pull_request_rules:
  - name: Automatically approve security PRs
    conditions:
      - author~=^(dependabot\[bot\]|renovate\[bot\])$
      - status-success=tests
    actions:
      merge:
        method: rebase
        rebase_fallback: squash
        bot_account: asset-tracker-cloud-ci
      label:
        add:
          - mergify
      rebase:
        bot_account: coderbyheart
